CREATE TABLE `gcd_topic` (
  `topic_id` varchar(30) NOT NULL,
  `hash_type` varchar(10) DEFAULT NULL,
  `rank` tinyint(4) NOT NULL DEFAULT '1',
  `title` varchar(1000) NOT NULL,
  `author` varchar(200) DEFAULT NULL,
  `brief` varchar(2000) DEFAULT NULL,
  `pubtime` datetime DEFAULT NULL,
  `updtime` datetime DEFAULT NULL,
  `main_category` varchar(50) DEFAULT NULL,
  `sub_category` varchar(50) DEFAULT NULL,
  `hash_link` text,
  `content` text,
  `related` varchar(2000) DEFAULT NULL,
  `res_site` varchar(10) DEFAULT NULL,
  `res_link` varchar(200) DEFAULT NULL,
  `abstract` varchar(2000) DEFAULT NULL,
  `res_id` varchar(30) DEFAULT NULL,
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`topic_id`),
  UNIQUE KEY `topic_id` (`topic_id`),
  KEY `index_hash_type` (`hash_type`),
  KEY `index_rank` (`rank`),
  KEY `index_pubtime` (`pubtime`),
  KEY `index_updtime` (`updtime`),
  KEY `index_main_category` (`main_category`),
  KEY `index_sub_category` (`sub_category`),
  KEY `ind_rank_main_sub_upd` (`rank`,`main_category`,`sub_category`,`updtime`),
  KEY `ind_rank_main_upd` (`rank`,`main_category`,`updtime`),
  KEY `ind_rank_id` (`rank`,`topic_id`),
  KEY `ind_rank_upd` (`rank`,`updtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ;
