CREATE TABLE `gcd_entry` (
  `entry_id` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `topic_id` varchar(30) NOT NULL,
  `res_site` varchar(10) DEFAULT NULL,
  `res_id` varchar(30) DEFAULT NULL,
  `title` varchar(1000) DEFAULT NULL,
  `author` varchar(200) DEFAULT NULL,
  `brief` varchar(2000) DEFAULT NULL,
  `abstract` varchar(2000) DEFAULT NULL,
  `pubtime` datetime NOT NULL,
  `updtime` datetime DEFAULT NULL,
  `res_link` varchar(200) DEFAULT NULL,
  `thumb_link` varchar(200) DEFAULT NULL,
  `image_link` varchar(200) DEFAULT NULL,
  `post_flag` int(11) DEFAULT '0',
  `posttime` datetime DEFAULT NULL,
  `thumb_flag` int(11) DEFAULT '0',
  `image_flag` int(11) DEFAULT '0',
  `fetch_flag` int(11) DEFAULT '0',
  `res_html` mediumtext,
  `entrytime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ext_text_1` varchar(2000) DEFAULT NULL,
  `ext_flag_1` int(11) DEFAULT '0',
  `ext_text_2` varchar(2000) DEFAULT NULL,
  `ext_flag_2` int(11) DEFAULT '0',
  PRIMARY KEY (`entry_id`),
  UNIQUE KEY `entry_id` (`entry_id`),
  KEY `site_id` (`res_id`),
  KEY `updtime` (`updtime`),
  KEY `res_site` (`res_site`),
  KEY `post_flag` (`post_flag`),
  KEY `thumb_flag` (`thumb_flag`),
  KEY `image_flag` (`image_flag`),
  KEY `fetch_flag` (`fetch_flag`),
  KEY `ext_flag_2` (`ext_flag_2`),
  KEY `ext_flag_1` (`ext_flag_1`),
  KEY `entrytime` (`entrytime`),
  UNIQUE KEY `topic_id_uni` (`topic_id`),
  KEY `topic_id` (`topic_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
